# Generated by Django 4.2.3 on 2023-07-17 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subtitle',
        ),
    ]
